#!/usr/bin/env bash
#
# Run all dotfiles installers.

warn () {
  printf "\r  [ \033[0;33m!\033[0m ] $1\n"
}


set -e

cd "$(dirname ${BASH_SOURCE[0]})"/..

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
